contexts_automap_p001 = [
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 0,
  'regionSource': 'ArtLayer armory r000',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 1,
  'regionSource': 'ArtLayer corridors r001',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 2,
  'regionSource': 'ArtLayer walkways r002',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 3,
  'regionSource': 'ArtLayer chapel r003',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 4,
  'regionSource': 'ArtLayer basement r004',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 5,
  'regionSource': 'ArtLayer library r005',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 6,
  'regionSource': 'ArtLayer vestibule r006',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 7,
  'regionSource': 'ArtLayer bell tower r007',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 8,
  'regionSource': 'ArtLayer workroom r008',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 10,
  'regionSource': 'ArtLayer warden r010',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 9,
  'regionSource': 'ArtLayer storage r009',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'region': 11,
  'regionSource': 'ArtLayer priest r011',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'language': 'italian',
  'languageSource': 'LayerSet italian',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'language': 'german',
  'languageSource': 'LayerSet german',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'language': 'french',
  'languageSource': 'LayerSet french',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'language': 'russian',
  'languageSource': 'LayerSet russian',
  },
  {
  'document': 'automap-p001.psd',
  'page': 1,
  'pageSource': 'Document automap-p001.psd',
  'language': 'english',
  'languageSource': 'LayerSet english',
  },
]
