//MISSION 12

//START
schema m12room1
archetype AMB_M12
poly_loop 2 4000 4500
pan_range 2000
volume -1000
howltxta howltxta voceerie

//HARSH
schema m12harsh
archetype AMB_M12
mono_loop 0 0
volume -1000
harsh1

//LEVEL 1
schema m12L1
archetype AMB_M12
poly_loop 2 5000 7000
pan_range 3000
volume -1500
cave1 cave2 cave3

schema m12trans
archetype AMB_M12
mono_loop 0 0
volume -1500
caveamb

schema m12cue1
archetype AMB_M12
volume -2000
ten9

schema m12cue2
archetype AMB_M12
volume -1000
howltxta howltxta voceerie

schema m12L1var
archetype AMB_M12
delay 2000
poly_loop 2 5000 20000
pan_range 2500
volume -1500
lo1 lo2 lo3 lo4 lo5

//BELLTHUMP
schema m12bellthump
archetype AMB_M12
volume -500
bellthmp

//FOR TREE ROOM
schema m12cicadas
archetype AMB_M14
volume -3000
poly_loop 2 2000 2500
cicad1 cicad2 cicad3 cicad4



//L2
schema m12L2
archetype AMB_M12
mono_loop 0 0 
volume -700
subson2

//feedback
schema m12fb
archetype AMB_M05
poly_loop 2 3000 4500
pan_range 3000
volume -1000
fb1 freq 2
fb2 freq 2
fb3 freq 2
fb4 freq 1


//space
schema M12vooh
archetype AMB_M12
volume -800
vooh


/////////
//HOUSE//
/////////




//WATER
schema m12watercalm
archetype AMB_M12
volume -2000
waterlp2

