//CONSTANTINE

//MISSION 14 -ENDGAME

//Alert 0
//schema cona0
//archetype CON_SPEECH
//mono_loop 5000 20000
//cona0_1 cona0_2 cona0_3
//schema_voice vcon 1 atlevelzero


//Ritual poem
schema conpom1
archetype CON_SPEECH
conpom1
schema_voice vcon 1 conpom1

schema conpom2
archetype CON_SPEECH
conpom2
schema_voice vcon 1 conpom2

schema conpom3
archetype CON_SPEECH
conpom3
schema_voice vcon 1 conpom3

schema conpom4
archetype CON_SPEECH
conpom4
schema_voice vcon 1 conpom4

schema conpom5
archetype CON_SPEECH
conpom5
schema_voice vcon 1 conpom5

schema conpom6
archetype CON_SPEECH
conpom6
schema_voice vcon 1 conpom6

//"Open for me..."
schema confin
archetype CON_SPEECH
confin
schema_voice vcon 1 confin
	
//"It...is...done!..."  
schema condone
archetype CON_SPEECH
condone
schema_voice vcon 1 condone
	
//"It betrays me!"
schema confail
archetype CON_SPEECH
confail
schema_voice vcon 1 confail

//"Garrett! My thiefsie fool!..."
schema consee1
archetype CON_SPEECH
consee1
schema_voice vcon 1 consee1

//"Comes chasing your death,..."
schema consee2
archetype CON_SPEECH
consee2
schema_voice vcon 1 consee2

//"Come calls your death now!"
schema consee3
archetype CON_SPEECH
consee3
schema_voice vcon 1 consee3

//"Your part is done."
schema consee4
archetype CON_SPEECH
consee4
schema_voice vcon 1 consee4










