//CUTTY - DEATH SCENE 

//Cutty hears Garrett
schema CUTM0301
archetype OTHER_CONV
cutm0301

//Cutty hears Garrett again
schema CUTM0302
archetype OTHER_CONV
cutm0302

//Conversation with Cutty
schema CUTC0102
archetype OTHER_CONV
cutc0102

schema CUTC0104
archetype OTHER_CONV
cutc0104

schema CUTC0105
archetype OTHER_CONV
cutc0105

schema CUTC0106
archetype OTHER_CONV
cutc0106

schema CUTC0107
archetype OTHER_CONV
cutc0107

schema CUTC0108
archetype OTHER_CONV
cutc0108


