//THE EYE

//Window Shopping	 

//"Comes a man to rescue me?..."
schema eye01
archetype PLAYER_SPEECH
eye01
schema_voice veye 1 eye01


//Steal the Eye 

//"SSSSSo, you've returned with the talismans..."	
schema eye02
archetype PLAYER_SPEECH
delay 2700
eye02
schema_voice veye 1 eye02

//"I am the Eye, trapped on this altar..."
schema eye03
archetype PLAYER_SPEECH
eye03
schema_voice veye 1 eye03

//"Well done, thief!  
schema eye04
archetype PLAYER_SPEECH
eye04
schema_voice veye 1 eye04
	
//"Leaving so soon?..."
schema eye05
archetype PLAYER_SPEECH
eye05
schema_voice veye 1 eye05

//"Where are you going?..."
schema eye06
archetype PLAYER_SPEECH
eye06
schema_voice veye 1 eye06

//"Poor Murus!  Still struggling.."
schema eye07
archetype PLAYER_SPEECH
eye07
schema_voice veye 1 eye07

//"Now you have your precious eye..."
schema eye08
archetype PLAYER_SPEECH
eye08
schema_voice veye 1 eye08

 	
//Endgame

//"Master!  Beware! .."	
schema eye09
archetype PLAYER_SPEECH
eye009
schema_voice veye 1 eye09
