//HAMMER CONVERSATIONS

////////////////////////////
//C06: "Dropping the Clue"//
////////////////////////////
		
schema hm1c0601
archetype HM_CONV
hm1c0601
schema_voice hammer1 1 hm_c06 (LineNo 1 1)

schema hm3c0602
archetype HM_CONV
hm3c0602
schema_voice hammer3 1 hm_c06 (LineNo 2 2)

schema hm1c0603
archetype HM_CONV
hm1c0603
schema_voice hammer1 1 hm_c06 (LineNo 3 3)

schema hm3c0604
archetype HM_CONV
hm3c0604
schema_voice hammer3 1 hm_c06 (LineNo 4 4)

//////////////////////////////////
//C07: "A curse upon this dust!"//
//////////////////////////////////

schema hm1c0701
archetype HM_CONV
hm1c0701
schema_voice hammer1 1 hm_c07 (LineNo 1 1)

schema hm2c0702
archetype HM_CONV
hm2c0702
schema_voice hammer2 1 hm_c07 (LineNo 2 2)

schema hm1c0703
archetype HM_CONV
hm1c0703
schema_voice hammer1 1 hm_c07 (LineNo 3 3)

schema hm2c0704
archetype HM_CONV
hm2c0704
schema_voice hammer2 1 hm_c07 (LineNo 4 4)

schema hm1c0705
archetype HM_CONV
hm1c0705
schema_voice hammer1 1 hm_c07 (LineNo 5 5)

////////////////////////////////
//C08: "Hast thought upon...?"//
////////////////////////////////

schema hm1c0801
archetype HM_CONV
hm1c0801
schema_voice hammer1 1 hm_c08 (LineNo 1 1)

schema hm3c0802
archetype HM_CONV
hm3c0802
schema_voice hammer3 1 hm_c08 (LineNo 2 2)

schema hm1c0803
archetype HM_CONV
hm1c0803
schema_voice hammer1 1 hm_c08 (LineNo 3 3)

schema hm3c0804
archetype HM_CONV
hm3c0804
schema_voice hammer3 1 hm_c08 (LineNo 4 4)

schema hm1c0805
archetype HM_CONV
hm1c0805
schema_voice hammer1 1 hm_c08 (LineNo 5 5)

/////////////////////////////////////////
//C09: "Even the Baron doth finally..."//
/////////////////////////////////////////

schema hm2c0901
archetype HM_CONV
hm2c0901
schema_voice hammer2 1 hm_c09 (LineNo 1 1)

schema hm1c0902
archetype HM_CONV
hm1c0902
schema_voice hammer1 1 hm_c09 (LineNo 2 2)

schema hm2c0903
archetype HM_CONV
hm2c0903
schema_voice hammer2 1 hm_c09 (LineNo 3 3)

schema hm1c0904
archetype HM_CONV
hm1c0904
schema_voice hammer1 1 hm_c09 (LineNo 4 4)

///////////////////////////////////
//C10: "Some do say the Baron..."//
///////////////////////////////////

schema hm3c1001
archetype HM_CONV
hm3c1001
schema_voice hammer3 1 hm_c10 (LineNo 1 1)

schema hm1c1002
archetype HM_CONV
hm1c1002
schema_voice hammer1 1 hm_c10 (LineNo 2 2)

schema hm3c1003
archetype HM_CONV
hm3c1003
schema_voice hammer3 1 hm_c10 (LineNo 3 3)

schema hm1c1004
archetype HM_CONV
hm1c1004
schema_voice hammer1 1 hm_c10 (LineNo 4 4)

////////////////////////////////////////
//C11: "Yet another sewer o’er flow.."//
////////////////////////////////////////

schema hm2c1101
archetype HM_CONV
hm2c1101
schema_voice hammer2 1 hm_c11 (LineNo 1 1)

schema hm3c1102
archetype HM_CONV
hm3c1102
schema_voice hammer3 1 hm_c11 (LineNo 2 2)

schema hm2c1103
archetype HM_CONV
hm2c1103
schema_voice hammer2 1 hm_c11 (LineNo 3 3)

schema hm3c1104
archetype HM_CONV
hm3c1104
schema_voice hammer3 1 hm_c11 (LineNo 4 4)

////////////////////////////////
//C12: "[grumpy] Time was...."//
////////////////////////////////

schema hm3c1201
archetype HM_CONV
hm3c1201
schema_voice hammer3 1 hm_c12 (LineNo 1 1)

schema hm2c1202
archetype HM_CONV
hm2c1202
schema_voice hammer2 1 hm_c12 (LineNo 2 2)

schema hm3c1203
archetype HM_CONV
hm3c1203
schema_voice hammer3 1 hm_c12 (LineNo 3 3)

/////////////////////////////////////////
//c13: "Heard thou? Tarius, seeking..."//
/////////////////////////////////////////

schema hm1c1301
archetype HM_CONV
hm1c1301
schema_voice hammer1 1 hm_c13 (LineNo 1 1)

schema hm2c1302
archetype HM_CONV
hm2c1302
schema_voice hammer2 1 hm_c13 (LineNo 2 2)

schema hm1c1303
archetype HM_CONV
hm1c1303
schema_voice hammer1 1 hm_c13 (LineNo 3 3)

schema hm2c1304
archetype HM_CONV
hm2c1304
schema_voice hammer2 1 hm_c13 (LineNo 4 4)

///////////////////////////////////////
//C14: "Time was, all these halls..."//
///////////////////////////////////////

schema hm1c1401
archetype HM_CONV
hm1c1401
schema_voice hammer1 1 hm_c14 (LineNo 1 1)

schema hm3c1402
archetype HM_CONV
hm3c1402
schema_voice hammer3 1 hm_c14 (LineNo 2 2)

schema hm1c1403
archetype HM_CONV
hm1c1403
schema_voice hammer1 1 hm_c14 (LineNo 3 3)

schema hm3c1404
archetype HM_CONV
hm3c1404
schema_voice hammer3 1 hm_c14 (LineNo 4 4)

////////////////////////////////
//C15: "Dolon hath told me..."//
////////////////////////////////

schema hm2c1501
archetype HM_CONV
hm2c1501
schema_voice hammer2 1 hm_c15 (LineNo 1 1)

schema hm3c1502
archetype HM_CONV
hm3c1502
schema_voice hammer3 1 hm_c15 (LineNo 2 2)

schema hm2c1503
archetype HM_CONV
hm2c1503
schema_voice hammer2 1 hm_c15 (LineNo 3 3)

schema hm3c1504
archetype HM_CONV
hm3c1504
schema_voice hammer3 1 hm_c15 (LineNo 4 4)
 
///////////////////////////////////////
//C16: Masterforger Dovetail hath..."//
///////////////////////////////////////

schema hm1c1601
archetype HM_CONV
hm1c1601
schema_voice hammer1 1 hm_c16 (LineNo 1 1)

schema hm3c1602
archetype HM_CONV
hm3c1602
schema_voice hammer3 1 hm_c16 (LineNo 2 2)

schema hm1c1603
archetype HM_CONV
hm1c1603
schema_voice hammer1 1 hm_c16 (LineNo 3 3)

//////////////////////////////////
//C17: "Builder walk with thee."//
//////////////////////////////////

schema hm1c1701
archetype HM_CONV
hm1c1701
schema_voice hammer1 1 hm_c17 (LineNo 1 1)

schema hm2c1702
archetype HM_CONV
hm2c1702
schema_voice hammer2 1 hm_c17 (LineNo 2 2)

////////////////////
//C18: "Good even"//
////////////////////

schema hm1c1801
archetype HM_CONV
hm1c1801
schema_voice hammer1 1 hm_c18 (LineNo 1 1)

schema hm2c1802
archetype HM_CONV
hm2c1802
schema_voice hammer2 1 hm_c18 (LineNo 2 2)

//////////////////////////////
//C19: "Praise the Builder!"//
//////////////////////////////

schema hm2c1901
archetype HM_CONV
hm2c1901
schema_voice hammer2 1 hm_c19 (LineNo 1 1)

schema hm1c1902
archetype HM_CONV
hm1c1902
schema_voice hammer1 1 hm_c19 (LineNo 2 2)

/////////////////////////////////////
//C20: "May thy hammer swing true."//
/////////////////////////////////////

schema hm2c2001
archetype HM_CONV
hm2c2001
schema_voice hammer2 1 hm_c20 (LineNo 1 1)

schema hm3c2002
archetype HM_CONV
hm3c2002
schema_voice hammer3 1 hm_c20 (LineNo 2 2)

/////////////////////////
//C21: "Hail, brother."//
/////////////////////////

schema hm2c2101
archetype HM_CONV
hm2c2101
schema_voice hammer2 1 hm_c21 (LineNo 1 1)

schema hm3c2102
archetype HM_CONV
hm3c2102
schema_voice hammer3 1 hm_c21 (LineNo 2 2)

///////////////////////////////////
//C22: "Builder’s grace to thee."//
///////////////////////////////////

schema hm3c2201
archetype HM_CONV
hm3c2201
schema_voice hammer3 1 hm_c22 (LineNo 1 1)

schema hm2c2202
archetype HM_CONV
hm2c2202
schema_voice hammer2 1 hm_c22 (LineNo 2 2)

/////////////////////
//C23: "Greetings."//
/////////////////////

schema hm3c2301
archetype HM_CONV
hm3c2201
schema_voice hammer3 1 hm_c23 (LineNo 1 1)

schema hm1c2302
archetype HM_CONV
hm1c2302
schema_voice hammer1 1 hm_c23 (LineNo 2 2)

//////////////////////////////////
//C24: "Builder guide thy hand."//
//////////////////////////////////

schema hm3c2401
archetype HM_CONV
hm3c2401
schema_voice hammer3 1 hm_c24 (LineNo 1 1)

schema hm1c2402
archetype HM_CONV
hm1c2402
schema_voice hammer1 1 hm_c24 (LineNo 2 2)

////////////////////////////////
//C25: "Be thy carving ready?"//
////////////////////////////////

schema hm1c2501
archetype HM_CONV
hm1c2501
schema_voice hammer1 1 hm_c25 (LineNo 1 1)

schema hm3c2502
archetype HM_CONV
hm3c2502
schema_voice hammer3 1 hm_c25 (LineNo 2 2)






