//MAGE CONVERSATIONS

//#104  "It's true he has returned. We must be ready."
schema mg110400
archetype OTHER_CONV
mg110400
schema_voice vmage1 1 mg_104 (LineNo 1 1)

schema mg210401
archetype OTHER_CONV
mg210401
schema_voice vmage2 1 mg_104 (LineNo 2 2)

schema mg110402
archetype OTHER_CONV
mg110402
schema_voice vmage1 1 mg_104 (LineNo 3 3)

schema mg210403
archetype OTHER_CONV
mg210403
schema_voice vmage2 1 mg_104 (LineNo 4 4)

schema mg110404
archetype OTHER_CONV
mg110404
schema_voice vmage1 1 mg_104 (LineNo 5 5)

schema mg210405
archetype OTHER_CONV
mg210405
schema_voice vmage2 1 mg_104 (LineNo 6 6)

schema mg110406
archetype OTHER_CONV
mg110406
schema_voice vmage1 1 mg_104 (LineNo 7 7)


//#106  "Librarian, hold. ..."
schema mg110600
archetype OTHER_CONV
mg110600
schema_voice vmage1 1 mg_106 (LineNo 1 1)

schema mg210601
archetype OTHER_CONV
mg210601
schema_voice vmage2 1 mg_106 (LineNo 2 2)

schema mg110602
archetype OTHER_CONV
mg110602
schema_voice vmage1 1 mg_106 (LineNo 3 3)

schema mg210603
archetype OTHER_CONV
mg210603
schema_voice vmage2 1 mg_106 (LineNo 4 4)

schema mg110604
archetype OTHER_CONV
mg110604
schema_voice vmage1 1 mg_106 (LineNo 5 5)

schema mg210605
archetype OTHER_CONV
mg210605
schema_voice vmage2 1 mg_106 (LineNo 6 6)

schema mg110606
archetype OTHER_CONV
mg110606
schema_voice vmage1 1 mg_106 (LineNo 7 7)

schema mg210607
archetype OTHER_CONV
mg210607
schema_voice vmage2 1 mg_106 (LineNo 8 8)



