//MURUS

//ALERT 0 MUTTERING
schema mura0mu1
archetype MURUS_SPEECH
mono_loop 1000 5000
mura0mu1 mura0mu2 mura0mu3 mura0mu4 mura0mu5 mura0mu6 silenc9s
schema_voice vmurus 1 murmut

//Intro	
schema murint
archetype MURUS_SPEECH
murint
schema_voice vmurus 1 murint

//Offering Garrett a deal	
schema murdeal
archetype MURUS_SPEECH
murdeal
schema_voice vmurus 1 murdeal

//Rosary	
schema murros1
archetype MURUS_SPEECH
murros1
schema_voice vmurus 1 murros1

//During Rosary	
schema murros2
archetype MURUS_SPEECH
murros2
schema_voice vmurus 1 murros2
	
//Post Rosary	
schema murros3
archetype MURUS_SPEECH
murros3
schema_voice vmurus 1 murros3

//HOLY SYMBOL	
schema mursym1
archetype MURUS_SPEECH
mursym1
schema_voice vmurus 1 mursym1

//DURING SYMBOL	
schema mursym2
archetype MURUS_SPEECH
mursym2
schema_voice vmurus 1 mursym2

//Post Symbol	
schema mursym3
archetype MURUS_SPEECH
mursym3
schema_voice vmurus 1 mursym3

//BOOK	
schema murbook1
archetype MURUS_SPEECH
murbook1
schema_voice vmurus 1 murbook1	

//DURING BOOK	
schema murbook2
archetype MURUS_SPEECH
murbook2
schema_voice vmurus 1 murbook2

//POST BOOK	
schema murbook3
archetype MURUS_SPEECH
murbook3
schema_voice vmurus 1 murbook3

//CANDLE	
schema murcand1
archetype MURUS_SPEECH
murcand1
schema_voice vmurus 1 murcand1

//DURING CANDLE	
schema murcand2
archetype MURUS_SPEECH
murcand2
schema_voice vmurus 1 murcand2

//POST CANDLE	
schema murcand3
archetype MURUS_SPEECH
murcand3
schema_voice vmurus 1 murcand3

//GRAVE	
schema murgrav
archetype MURUS_SPEECH
murgrav
schema_voice vmurus 1 murgrav

//RITUAL BEADS	
schema murrit1
archetype MURUS_SPEECH
murrit1
schema_voice vmurus 1 murrit1

//RITUAL CANDLE	
schema murrit2
archetype MURUS_SPEECH
murrit2
schema_voice vmurus 1 murrit2

//RITUAL BOOK	
schema murrit3
archetype MURUS_SPEECH
murrit3
schema_voice vmurus 1 murrit3

//RITUAL SYMBOL	
schema murrit4
archetype MURUS_SPEECH
murrit4
schema_voice vmurus 1 murrit4

//SYMBOL IS BAD 	
schema murbad
archetype MURUS_SPEECH
murbad
schema_voice vmurus 1 murbad
	
//RITUAL COMPLETE	
schema murrit5
archetype MURUS_SPEECH
murrit5
schema_voice vmurus 1 murrit5

//BURIAL
schema murbur
archetype MURUS_SPEECH
murbur
schema_voice vmurus 1 murbur

//RENAULT 1
schema murren1
archetype MURUS_SPEECH
murren1
schema_voice vmurus 1 murren1

//RENAULT 2
schema murren2
archetype MURUS_SPEECH
murren2
schema_voice vmurus 1 murren2

//MARTELLO	
schema murmart
archetype MURUS_SPEECH
murmart
schema_voice vmurus 1 murmart

//HAUNTS	
schema murhau1
archetype MURUS_SPEECH
murhau1
schema_voice vmurus 1 murhau1

//HAUNTS 2	
schema murhau2
archetype MURUS_SPEECH
murhau2
schema_voice vmurus 1 murhau2

//FINAL	
schema murfin	
archetype MURUS_SPEECH
murfin
schema_voice vmurus 1 murfin

