//OPERA CONVERSATIONS

//#124  "[Singing] But wait!  Who is this I spy?"
schema op212400
archetype OTHER_CONV
op212400
schema_voice vactor2 1 op_124 (LineNo 1 1)

schema op112401
archetype OTHER_CONV
op112401
schema_voice vactor1 1 op_124 (LineNo 2 2)

schema op212402
archetype OTHER_CONV
op212402
schema_voice vactor2 1 op_124 (LineNo 3 3)

schema op112403
archetype OTHER_CONV
op112403
schema_voice vactor1 1 op_124 (LineNo 4 4)

schema op212404
archetype OTHER_CONV
op212404
schema_voice vactor2 1 op_124 (LineNo 5 5)

schema op112405
archetype OTHER_CONV
op112405
schema_voice vactor1 1 op_124 (LineNo 6 6)

schema op212406
archetype OTHER_CONV
op212406
schema_voice vactor2 1 op_124 (LineNo 7 7)



//#125  "Did you read Cribs latest?"  
schema op112500
archetype OTHER_CONV
op112500
schema_voice vactor1 1 op_125 (LineNo 1 1)

schema op212501
archetype OTHER_CONV
op212501
schema_voice vactor2 1 op_125 (LineNo 2 2)

schema op112502
archetype OTHER_CONV
op112502
schema_voice vactor1 1 op_125 (LineNo 3 3)

schema op212503
archetype OTHER_CONV
op212503
schema_voice vactor2 1 op_125 (LineNo 4 4)

schema op112504
archetype OTHER_CONV
op112504
schema_voice vactor1 1 op_125 (LineNo 5 5 )

schema op212505
archetype OTHER_CONV
op212505
schema_voice vactor2 1 op_125 (LineNo 6 6)



//#126  "This latest opera from Valerius and Cribs is a testament..."
schema op112600
archetype OTHER_CONV
op112600
schema_voice vpatron1 1 op_126 (LineNo 1 1)

schema op212601
archetype OTHER_CONV
op212601
schema_voice vpatron2 1 op_126 (LineNo 2 2)

schema op112602
archetype OTHER_CONV
op112602
schema_voice vpatron1 1 op_126 (LineNo 3 3)

schema op212603
archetype OTHER_CONV
op212603
schema_voice vpatron2 1 op_126 (LineNo 4 4)

schema op112604
archetype OTHER_CONV
op112604
schema_voice vpatron1 1 op_126 (LineNo 5 5)







