//GUARD CONVERSATIONS

//////////////////////////////////
//C01: "They don't make bears...//
//////////////////////////////////
		
schema sg3c0101
archetype SG_CONV
sg3c0101
schema_voice guard3 1 sg_c01 (LineNo 1 1)

schema sg2c0102
archetype SG_CONV
sg2c0102
schema_voice guard2 1 sg_c01 (LineNo 2 2)

schema sg3c0103
archetype SG_CONV
sg3c0103
schema_voice guard3 1 sg_c01 (LineNo 3 3)

schema sg2c0104
archetype SG_CONV
sg2c0104
schema_voice guard2 1 sg_c01 (LineNo 4 4)

schema sg3c0105
archetype SG_CONV
sg3c0105
schema_voice guard3 1 sg_c01 (LineNo 5 5)

schema sg2c0106
archetype SG_CONV
sg2c0106
schema_voice guard2 1 sg_c01 (LineNo 6 6)

schema sg3c0107
archetype SG_CONV
sg3c0107
schema_voice guard3 1 sg_c01 (LineNo 7 7)

schema sg2c0108
archetype SG_CONV
sg2c0108
schema_voice guard2 1 sg_c01 (LineNo 8 8)

schema sg3c0109
archetype SG_CONV
sg3c0109
schema_voice guard3 1 sg_c01 (LineNo 9 9)

schema sg2c0110
archetype SG_CONV
sg2c0110
schema_voice guard2 1 sg_c01 (LineNo 10 10)

schema sg3c0111
archetype SG_CONV
sg3c0111
schema_voice guard3 1 sg_c01 (LineNo 11 11)

////////////////////////////////////////////
//C07: "Nothing ever happens on this job."//
////////////////////////////////////////////

schema sg1c0701
archetype SG_CONV
sg1c0701
schema_voice guard1 1 sg_c07 (LineNo 1 1)

schema sg2c0702
archetype SG_CONV
sg2c0702
schema_voice guard2 1 sg_c07 (LineNo 2 2)

schema sg1c0703
archetype SG_CONV
sg1c0703
schema_voice guard1 1 sg_c07 (LineNo 3 3)

schema sg2c0704
archetype SG_CONV
sg2c0704
schema_voice guard2 1 sg_c07 (LineNo 4 4)

schema sg1c0705
archetype SG_CONV
sg1c0705
schema_voice guard1 1 sg_c07 (LineNo 5 5)

schema sg2c0706
archetype SG_CONV
sg2c0706
schema_voice guard2 1 sg_c07 (LineNo 6 6)

schema sg1c0707
archetype SG_CONV
sg1c0707
schema_voice guard1 1 sg_c07 (LineNo 7 7)

////////////////////////////////////////
//C08: "You get any pheasant tonight?"//
////////////////////////////////////////

schema sg1c0801
archetype SG_CONV
sg1c0801
schema_voice guard1 1 sg_c08 (LineNo 1 1)

schema sg2c0802
archetype
archetype SG_CONV
sg2c0802
schema_voice guard2 1 sg_c08 (LineNo 2 2)

schema sg1c0803
archetype SG_CONV
sg1c0803
schema_voice guard1 1 sg_c08 (LineNo 3 3)

schema sg2c0804
archetype SG_CONV
sg2c0804
schema_voice guard2 1 sg_c08 (LineNo 4 4)

schema sg1c0805
archetype SG_CONV
sg1c0805
schema_voice guard1 1 sg_c08 (LineNo 5 5)

schema sg2c0806
archetype SG_CONV
sg2c0806
schema_voice guard2 1 sg_c08 (LineNo 6 6)

schema sg1c0807
archetype SG_CONV
sg1c0807
schema_voice guard1 1 sg_c08 (LineNo 7 7)

/////////////////////////////////////
//C09: "I thought Quince & Jaco..."//
/////////////////////////////////////

schema sg1c0901
archetype SG_CONV
sg1c0901
schema_voice guard1 1 sg_c09 (LineNo 1 1)

schema sg2c0902
archetype SG_CONV
sg2c0902
schema_voice guard2 1 sg_c09 (LineNo 2 2)

schema sg1c0903
archetype SG_CONV
sg1c0903
schema_voice guard1 1 sg_c09 (LineNo 3 3)

schema sg2c0904
archetype SG_CONV
sg2c0904
schema_voice guard2 1 sg_c09 (LineNo 4 4)

/////////////////////////////////////////////
//C10: "Say, where are Hal & Joss tonight?"//
/////////////////////////////////////////////

schema sg1c1001
archetype SG_CONV
sg1c1001
schema_voice guard1 1 sg_c10 (LineNo 1 1)

schema sg1c1002
archetype SG_CONV
sg2c1002
schema_voice guard2 1 sg_c10 (LineNo 2 2)

schema sg1c1003
archetype SG_CONV
sg1c1003
schema_voice guard1 1 sg_c10 (LineNo 3 3)

schema sg2c1004
archetype SG_CONV
sg2c1004
schema_voice guard2 1 sg_c10 (LineNo 4 4)

schema sg1c1005
archetype SG_CONV
sg1c1005
schema_voice guard1 1 sg_c10 (LineNo 5 5)

//////////////////////////////////////
//C11: "Hey, go down to the well..."//
//////////////////////////////////////

schema sg2c1101
archetype SG_CONV
sg2c1101
schema_voice guard2 1 sg_c11 (LineNo 1 1)

schema sg3c1102
archetype SG_CONV
sg3c1102
schema_voice guard3 1 sg_c11 (LineNo 2 2)

/////////////////////////////////////////////
//C12: "I hear you're gonna be assigned..."//
/////////////////////////////////////////////

schema sg1c1201
archetype SG_CONV
sg1c1201
schema_voice guard1 1 sg_c12 (LineNo 1 1)

schema sg2c1202
archetype SG_CONV
sg2c1202
schema_voice guard2 1 sg_c12 (LineNo 2 2)

schema sg1c1203
archetype SG_CONV
sg1c1203
schema_voice guard1 1 sg_c12 (LineNo 3 3)

schema sg2c1204
archetype SG_CONV
sg2c1204
schema_voice guard2 1 sg_c12 (LineNo 4 4)

////////////////////////////////////////////
//C13: "You seen the stuff Shemenov's...?"//
////////////////////////////////////////////

schema sg2c1301
archetype SG_CONV
sg2c1301
schema_voice guard2 1 sg_c13 (LineNo 1 1)

schema sg1c1302
archetype SG_CONV
sg1c1302
schema_voice guard1 1 sg_c13 (LineNo 2 2)

schema sg2c1303
archetype SG_CONV
sg2c1303
schema_voice guard2 1 sg_c13 (LineNo 3 3)

schema sg1c1304
archetype SG_CONV
sg1c1304
schema_voice guard1 1 sg_c13 (LineNo 4 4)

////////////////////////////////////////
//C14: "I hear Granmauden is gonna..."//
////////////////////////////////////////

schema sg1c1401
archetype SG_CONV
sg1c1401
schema_voice guard1 1 sg_c14 (LineNo 1 1)

schema sg3c1402
archetype SG_CONV
sg3c1402
schema_voice guard3 1 sg_c14 (LineNo 2 2)

schema sg1c1403
archetype SG_CONV
sg1c1403
schema_voice guard1 1 sg_c14 (LineNo 3 3)

schema sg3c1404
archetype SG_CONV
sg3c1404
schema_voice guard3 1 sg_c14 (LineNo 4 4)

schema sg1c1405
archetype SG_CONV
sg1c1405
schema_voice guard1 1 sg_c14 (LineNo 5 5)

schema sg3c1406
archetype SG_CONV
sg3c1406
schema_voice guard3 1 sg_c14 (LineNo 6 6)

////////////////////////////
//C15: "Jorik tells me..."//
////////////////////////////

schema sg3c1501
archetype SG_CONV
sg3c1501
schema_voice guard3 1 sg_c15 (LineNo 1 1)

schema sg1c1502
archetype SG_CONV
sg1c1502
schema_voice guard1 1 sg_c15 (LineNo 2 2)

schema sg3c1503
archetype SG_CONV
sg3c1503
schema_voice guard3 1 sg_c15 (LineNo 3 3)

schema sg1c1504
archetype SG_CONV
sg1c1504
schema_voice guard1 1 sg_c15 (LineNo 4 4)

///////////////////////////////
//C16: "Hear you got a pool."//
///////////////////////////////

schema sg2c1601
archetype SG_CONV
sg2c1601
schema_voice guard2 1 sg_c16 (LineNo 1 1)

schema sg3c1602
archetype SG_CONV
sg3c1602
schema_voice guard3 1 sg_c16 (LineNo 2 2)

schema sg2c1603
archetype SG_CONV
sg2c1603
schema_voice guard2 1 sg_c16 (LineNo 3 3)

schema sg3c1604
archetype SG_CONV
sg3c1604
schema_voice guard3 1 sg_c16 (LineNo 4 4)

schema sg2c1605
archetype SG_CONV
sg2c1605
schema_voice guard2 1 sg_c16 (LineNo 5 5)

////////////////////////////////////////////////
//C17: "Hey, you remember when the Baron's..?"//
////////////////////////////////////////////////

schema sg3c1701
archetype SG_CONV
sg3c1701
schema_voice guard3 1 sg_c17 (LineNo 1 1)

schema sg2c1702
archetype SG_CONV
sg2c1702
schema_voice guard2 1 sg_c17 (LineNo 2 2)

schema sg3c1703
archetype SG_CONV
sg3c1703
schema_voice guard3 1 sg_c17 (LineNo 3 3)

schema sg2c1074
archetype SG_CONV
sg2c1074
schema_voice guard2 1 sg_c17 (LineNo 4 4)

///////////////////////////////////////////
//C18: "So I hear the guys that clean..."//
///////////////////////////////////////////

schema sg1c1801
archetype SG_CONV
sg1c1801
schema_voice guard1 1 sg_c18 (LineNo 1 1)

schema sg2c1802
archetype SG_CONV
sg2c1802
schema_voice guard2 1 sg_c18 (LineNo 2 2)

schema sg1c1803
archetype SG_CONV
sg1c1803
schema_voice guard1 1 sg_c18 (LineNo 3 3)

schema sg2c1804
archetype SG_CONV
sg2c1804
schema_voice guard2 1 sg_c18 (LineNo 4 4)

schema sg1c1805
archetype SG_CONV
sg1c1805
schema_voice guard1 1 sg_c18 (LineNo 5 5)

/////////////////////////////////////////
//C19: "I've been thinking, the Sir..."//
/////////////////////////////////////////

schema sg1c1901
archetype SG_CONV
sg1c1901
schema_voice guard1 1 sg_c19 (LineNo 1 1)

schema sg3c1902
archetype SG_CONV
sg3c1902
schema_voice guard3 1 sg_c19 (LineNo 2 2)

schema sg1c1903
archetype SG_CONV
sg1c1903
schema_voice guard1 1 sg_c19 (LineNo 3 3)

schema sg3c1904
archetype SG_CONV
sg3c1904
schema_voice guard3 1 sg_c19 (LineNo 4 4)

schema sg1c1905
archetype SG_CONV
sg1c1905
schema_voice guard1 1 sg_c19 (LineNo 5 5)

schema sg3c1906
archetype SG_CONV
sg3c1906
schema_voice guard3 1 sg_c19 (LineNo 6 6)

//////////////////////////////////
//C20: "So I was telling you..."//
//////////////////////////////////

schema sg2c2001
archetype SG_CONV
sg2c2001
schema_voice guard2 1 sg_c20 (LineNo 1 1)

schema sg3c2002
archetype SG_CONV
sg3c2002
schema_voice guard3 1 sg_c20 (LineNo 2 2)

schema sg2c2003
archetype SG_CONV
sg2c2003
schema_voice guard2 1 sg_c20 (LineNo 3 3)

schema sg3c2004
archetype SG_CONV
sg3c2004
schema_voice guard3 1 sg_c20 (LineNo 4 4)

//CON'S GUARDS

//////////////////////////////////
//C21: "Can't stand the food..."//
//////////////////////////////////

schema sg1c2101
archetype SG_CONV
sg1c2101
schema_voice guard1 1 sg_c21 (LineNo 1 1)

schema sg2c2102
archetype SG_CONV
sg2c2102
schema_voice guard2 1 sg_c21 (LineNo 2 2)

schema sg1c2103
archetype SG_CONV
sg1c2103
schema_voice guard1 1 sg_c21 (LineNo 3 3)

////////////////////////////////////
//C22: "Think anything'll happen?"//
////////////////////////////////////

schema sg2c2201
archetype SG_CONV
sg2c2201
schema_voice guard2 1 sg_c22 (LineNo 1 1)

schema sg1c2202
archetype SG_CONV
sg1c2202
schema_voice guard1 1 sg_c22 (LineNo 2 2)

schema sg2c2203
archetype SG_CONV
sg2c2203
schema_voice guard2 1 sg_c22 (LineNo 3 3)

//////////////////////////////////
//C23: "Boss's dangerous today."//
//////////////////////////////////

schema sg1c2301
archetype SG_CONV
sg1c2301
schema_voice guard1 1 sg_c23 (LineNo 1 1)

schema sg3c2302
archetype SG_CONV
sg3c2302
schema_voice guard3 1 sg_c23 (LineNo 2 2)

schema sg1c2303
archetype SG_CONV
sg1c2303
schema_voice guard1 1 sg_c23 (LineNo 3 3)

////////////////////////////////
//C24: "Seen the new room...?"//
////////////////////////////////

schema sg3c2401
archetype SG_CONV
sg3c2401
schema_voice guard3 1 sg_c24 (LineNo 1 1)

schema sg1c2402
archetype SG_CONV
sg1c2402
schema_voice guard1 1 sg_c24 (LineNo 2 2)

schema sg3c2403
archetype SG_CONV
sg3c2403
schema_voice guard3 1 sg_c24 (LineNo 3 3)

//////////////////////////////////
//C25: "I think you're a-sleepy"//
//////////////////////////////////

schema sg2c2501
archetype SG_CONV
sg2c2501
schema_voice guard2 1 sg_c25 (LineNo 1 1)

schema sg3c2502
archetype SG_CONV
sg3c2502
schema_voice guard3 1 sg_c25 (LineNo 2 2)

schema sg2c2503
archetype SG_CONV
sg2c2503
schema_voice guard2 1 sg_c25 (LineNo 3 3)

////////////////////////////////////
//C26: "I can't believe how bad.."//
////////////////////////////////////

schema sg1c2601
archetype SG_CONV
sg1c2601
schema_voice guard1 1 sg_c26 (LineNo 1 1)

schema sg2c2602
archetype SG_CONV
sg2c2602
schema_voice guard2 1 sg_c26 (LineNo 2 2)

schema sg1c2603
archetype SG_CONV
sg1c2603
schema_voice guard1 1 sg_c26 (LineNo 3 3)

schema sg2c2604
archetype SG_CONV
sg2c2604
schema_voice guard2 1 sg_c26 (LineNo 4 4)

//Teeny Conversations

//////////////////////////
//C30: "How's it going?"//
//////////////////////////

schema sg1c3001
archetype SG_CONV
sg1c3001
schema_voice guard1 1 sg_c30 (LineNo 1 1)

schema sg2c3002
archetype SG_CONV
sg2c3002
schema_voice guard2 1 sg_c30 (LineNo 2 2)

//////////////////////
//C31: "Good watch."//
//////////////////////

schema sg1c3101
archetype SG_CONV
sg1c3101
schema_voice guard1 1 sg_c31 (LineNo 1 1)

schema sg2c3102
archetype SG_CONV
sg2c3102
schema_voice guard2 1 sg_c31 (LineNo 2 2)

/////////////////////////
//C32: "Seen anything?"//
/////////////////////////

schema sg2c3201
archetype SG_CONV
sg2c3201
schema_voice guard2 1 sg_c32 (LineNo 1 1)

schema sg1c3202
archetype SG_CONV
sg1c3202
schema_voice guard1 1 sg_c32 (LineNo 2 2)

//////////////////////
//C33: "Nice night."//
//////////////////////

schema sg2c3301
archetype SG_CONV
sg2c3301
schema_voice guard2 1 sg_c33 (LineNo 1 1)

schema sg3c3302
archetype SG_CONV
sg3c3302
schema_voice guard3 1 sg_c33 (LineNo 2 2)

/////////////////////////////
//C34: "All's well my way."//
/////////////////////////////

schema sg2c3401
archetype SG_CONV
sg2c3401
schema_voice guard2 1 sg_c34 (LineNo 1 1)

schema sg3c3402
archetype SG_CONV
sg3c3402
schema_voice guard3 1 sg_c34 (LineNo 2 2)

/////////////////////////////////
//C35: "Hail, brother-in-arms!"//
/////////////////////////////////

schema sg3c3501
archetype SG_CONV
sg3c3501
schema_voice guard3 1 sg_c35 (LineNo 1 1)

schema sg2c3502
archetype SG_CONV
sg2c3502
schema_voice guard2 1 sg_c35 (LineNo 2 2)

/////////////////////
//C36: "What's up?"//
/////////////////////

schema sg3c3601
archetype SG_CONV
sg3c3601
schema_voice guard3 1 sg_c36 (LineNo 1 1)

schema sg1c3602
archetype SG_CONV
sg1c3602
schema_voice guard1 1 sg_c36 (LineNo 2 2)

//////////////////////////////
//C37: "I hate night watch."//
//////////////////////////////

schema sg1c3701
archetype SG_CONV
sg1c3701
schema_voice guard1 1 sg_c37 (LineNo 1 1)

schema sg3c3702
archetype SG_CONV
sg3c3702
schema_voice guard3 1 sg_c37 (LineNo 2 2)

////////////////////////////////
//C38: "Halt, who goes there?"//
////////////////////////////////

schema sg3c3801
archetype SG_CONV
sg3c3801
schema_voice guard3 1 sg_c38 (LineNo 1 1)

schema sg1c3802
archetype SG_CONV
sg1c3802
schema_voice guard1 1 sg_c38 (LineNo 2 2)


///////////////////////////////////////////////////////////
//123: Just so's you're clear, if there's any trouble..."//
///////////////////////////////////////////////////////////

schema sg112300
archetype SG_CONV
sg112300
schema_voice guard1 1 sg_123 (LineNo 1 1)

schema sg312301
archetype SG_CONV
sg312301
schema_voice guard3 1 sg_123 (LineNo 2 2)

schema sg112302
archetype SG_CONV
sg112302
schema_voice guard1 1 sg_123 (LineNo 3 3)

schema sg312303
archetype SG_CONV
sg312303
schema_voice guard3 1 sg_123 (LineNo 4 4)

schema sg112304
archetype SG_CONV
sg112304
schema_voice guard1 1 sg_123 (LineNo 5 5)

schema sg312305
archetype SG_CONV
sg312305
schema_voice guard3 1 sg_123 (LineNo 6 6)

schema sg112306
archetype SG_CONV
sg112306
schema_voice guard1 1 sg_123 (LineNo 7 7)


//////////////////////////////////////////////////////////////
//101: But why are the Hand Mages the only ones allowed in? //
//////////////////////////////////////////////////////////////

schema sg310100
archetype SG_CONV
sg310100
schema_voice guard3 1 sg_101 (LineNo 1 1)

schema sg110101
archetype SG_CONV
sg110101
schema_voice guard1 1 sg_101 (LineNo 2 2)

schema sg310102
archetype SG_CONV
sg310102
schema_voice guard3 1 sg_101 (LineNo 3 3)

schema sg110103
archetype SG_CONV
sg110103
schema_voice guard1 1 sg_101 (LineNo 4 4)


////////////////////////////////////////////////////
//102: These mages aren't ones to be trifled with //
////////////////////////////////////////////////////

schema sg310200
archetype SG_CONV
sg310200
schema_voice guard3 1 sg_102 (LineNo 1 1)

schema sg110201
archetype SG_CONV
sg110201
schema_voice guard1 1 sg_102 (LineNo 2 2)


/////////////////////////////////
//062: These pressure doors... //
/////////////////////////////////

schema sg306200
archetype SG_CONV
sg306200
schema_voice guard3 1 sg_062 (LineNo 1 1)

schema sg106201
archetype SG_CONV
sg106201
schema_voice guard1 1 sg_062 (LineNo 2 2)

schema sg306202
archetype SG_CONV
sg306202
schema_voice guard3 1 sg_062 (LineNo 3 3)

schema sg106203
archetype SG_CONV
sg106203
schema_voice guard1 1 sg_062 (LineNo 4 4)

schema sg306204
archetype SG_CONV
sg306204
schema_voice guard3 1 sg_062 (LineNo 5 5)


////////////////////////////////////////////
//064: Donal & Ruben can kil each other...//
////////////////////////////////////////////

schema sg106400
archetype SG_CONV
sg106400
schema_voice guard1 1 sg_064 (LineNo 1 1)

schema sg306401
archetype SG_CONV
sg306401
schema_voice guard3 1 sg_064 (LineNo 2 2)

schema sg106402
archetype SG_CONV
sg106402
schema_voice guard1 1 sg_064 (LineNo 3 3)

schema sg306403
archetype SG_CONV
sg306403
schema_voice guard3 1 sg_064 (LineNo 4 4)