////////////
//CONCEPTS//
////////////

//BROADCAST CONCEPTS
concept sleeping 1
concept atlevelzero 1
concept atlevelone 3		//was 1
concept atleveltwo 2		//was 1
concept atlevelthree 1
concept tolevelone 5
concept toleveltwo 5
concept noticetorch 5
concept tolevelthree 5	
concept spotplayer 6
concept reactcharge 2		//was 2
concept reactshoot 2		//was 2
concept reactrun 2		
concept reactwarn 5		//was 2
concept reactwarn2 5		//was 2
concept reactalarm 2		//was 2
concept reacttellrev 2		//was 2
concept reacttellconf 2		//was 2
concept outofreach 4		
concept backtozero 5		//was 2	
concept lostcontact 4		//was 3
concept foundbody	5		
concept foundmissing 5		//was 3  	
concept foundbreach 5		//was 3	
concept foundsmall 5		//was 3
concept foundlarge 5		//was 3	
concept recentintruder 5	//was 3
concept recentbody 5		//was 3
concept recentmissing 5		//was 3
concept recentother 5		//was 3
concept comattack	8
concept comsucchit 8	
concept comsuccblock 8	
concept comdetblock 8	
concept comblocked 8	
concept comhitnodam 8
concept comhithigh 9
concept comhitlow	9
concept comhitamb	9
concept comdieloud 10
concept comdiesoft 10

//CONVERSATION CONCEPTS

//GUARD CONVERSATIONS
concept sg_c01 4	//"They don't make bears..."
concept sg_c07 4	//"Nothing ever happens on this job."
concept sg_c08 4	//"You get any pheasant.."
concept sg_c09 4	//"I thought Quince & Jaco..."
concept sg_c10 4	//"Say, where are Hal & Joss..."
concept sg_c11 4	//"Hey, go down to the well..."
concept sg_c12 4	//"I hear you're gonna be assigned..."
concept sg_c13 4	//"You seen the stuff Shemenov's...?"
concept sg_c14 4	//"I hear Granmauden is gonna..."
concept sg_c15 4	//"Jorik tells me..."
concept sg_c16 4	//"Hear you got a pool."
concept sg_c17 4	//"Hey, you remember when the Baron's..?"
concept sg_c18 4	//"So I hear the guys that clean..."
concept sg_c19 4	//"I've been thinking, the Sir..."
concept sg_c20 4	//"So I was telling you..."
concept sg_c21 4	//"Can't stand the food..."
concept sg_c22 4	//"Think anything'll happen?"
concept sg_c23 4	//"Boss's dangerous today."
concept sg_c24 4	//"Seen the new room...?"
concept sg_c25 4	//"I think you're a-sleepy"
concept sg_c26 4	//"I can't believe how bad.."
concept sg_c30 4	//"How's it going?"
concept sg_c31 4	//"Good watch."
concept sg_c32 4	//"Seen anything?"
concept sg_c33 4	//"Nice night."
concept sg_c34 4	//"All's well my way."
concept sg_c35 4	//"Hail, brother-in-arms!"
concept sg_c36 4	//"What's up?"
concept sg_c37 4	//"I hate night watch."
concept sg_c38 4	//"Halt, who goes there?"
concept sg_123 4	//"Just so's you're clear, if there's any trouble..." 
concept sg_101 4	//"But why are the Hand Mages the only ones allowed in?"
concept sg_102 4	//"Theses mages are not ones to be trifled with."
concept sg_062 4	//"These pressure doors are a bloody nuisance."
concept sg_064 4	//"Donal and Ruben can kill each other for all I care."

//HAMMER CONVERSATIOINS
concept hm_c06 4	//"Dropping the Clue"
concept hm_c07 4	//"A curse upon this dust!"
concept hm_c08 4	//"Hast thought upon.."
concept hm_c09 4	//"Even the Baron..."
concept hm_c10 4	//"Some do say the Baron.."
concept hm_c11 4	//"Yet another sewer o'er flow..."
concept hm_c12 4	//"Time was, the sinners..."
concept hm_c13 4	//"Heard thou? Tarius..."
concept hm_c14 4	//"Time was, all these halls..."
concept hm_c15 4	//"Dolon hath told me,"
concept hm_c16 4	//"Masterforger Dovetail..."
concept hm_c17 4 	//"Builder walk with thee."
concept hm_c18 4	//"Good even." 
concept hm_c19 4	//"Praise the Builder!"
concept hm_c20 4	//"May thy hammer swing true."
concept hm_c21 4	//"Hail, brother."
concept hm_c22 4	//"Builder's grace to thee."
concept hm_c23 4	//"Greetings."
concept hm_c24 4	//"Builder guide thy hand."
concept hm_c25 4	//"Be thy carving ready?"

//SERVANT CONVERSATIONS
concept sv_c01 4	
concept sv_c02 4		
concept sv_c03 4	
concept sv_c04 4	
concept sv_c05 4
concept sv_c06 4
concept sv_c07 4
concept sv_c08 4
concept sv_c09 4
concept sv_c10 4
concept sv_c11 4
concept sv_c12 4
concept sv_c13 4
concept sv_c14 4
concept sv_c15 4
concept sv_c16 4
concept sv_c17 4
concept sv_c18 4
concept sv_c19 4
concept sv_063 4 //"Hit me."

//OPERA PEOPLE CONVERSATIONS
concept op_124 4 //"[Singing] But wait!  Who is this I spy?"
concept op_125 4 //"Did you read Cribs latest?"  
concept op_126 4 //"This latest opera from Valerius..."


//THIEVES' CONVERSATIONS
concept th_061 4 //"When partners fight..."
concept th_065 4 //"By the builder I will find you..."
concept th_066 4 //"I hear some independent..."
concept th_067 4 //"Bafford was furious when he got back..."
concept th_068 4 //"Did you here what happened to Gibbson.."
concept th_069 4 //"Y'hear about Sutter's job last night?"
concept th_071 4 //"Password?"

//MAGES' CONVERSATIONS
concept mg_104 4 //"It's true he has returned..."
concept mg_106 4 //"Librarian, hold..."	


		

//MISSION SPECIFIC CONCEPTS

//MISSION 2
concept SV_M0201 4 	//the stove is out again
concept DrunkA3 4		//"Crazy Getup"

concept SG_M0201 4
concept SG_M0202 4
concept SG_M0203 4	//1st guard says "hello"
concept sg2m02D1 4


//MISSION 5
concept SV_M0501 4	//Carrying the tray, complaining	
concept SV_M0503 8	//Ramirez is missing

concept SG_M0502 9	//Guards seeing Garrett exit bldg.

//MISSION 10
concept m1001 4	//you're discovered to be a spy
concept m1002 4	//you're caught loitering
concept m1003 4	//you're caught in the barracks
concept m1004 4	//fetch me the candlestick
concept m1005 4	//put ze candle bak!
concept m1006 4	//what's your hurry?
concept m1007 4	//Hello novice.
concept m1008 4	//Builder's strength to you too.
concept m1009 4 	//Open the gate
concept m1010 4 	//Present your credentials, lad

//MISSION 13
concept m1302 4  	//"Waste no more time..."
concept m1303 4   //"Wait! Thou art going the wrong way!"
concept m1304 4   //"Thank the Builder! Our High Priest..."
concept m1305 4	//"Tis thee, the Master Thief..."
concept m1306 4	//"The Trickster's beasts hath captured..."
concept m1307 4 	//"We lack thy skills of stealth..." 
concept m1308 4	//"Take this key and map, and go."
concept m1309 4	//"Also, our enemies hold the Builder's Chisel"
concept m1310 4	//"Thou hast rescued our High Priest"
concept m1311 4	//"Thank thee for not killing this one."
concept m1312 4	//"Thy recovery of the chisel is provident"
concept m1313 4	//"Thank the Builder! Not only hast thou returned..."

//MISSION 14
//CON SPEECH
concept conpom1 4		//"Vine, grow and twine,..."	
concept conpom2 4		//"Storm, black and blow,..."	
concept conpom3 4		//"Flame, burning heat,..."
concept conpom4 4		//"Tide, rise and fall,..."
concept conpom5 4		//"Stone, grind and quake,..."
concept conpom6 4		//"Night, smother light,..."
concept confin 4		//"Open for me..."
concept condone 4		//"It...is...done!..."  
concept confail 4		//"It betrays me!"
concept consee1 5		//"Garrett! My thiefsie fool!..."
concept consee2 5		//"Comes chasing your death,..."
concept consee3 5		//"Come calls your death now!"
concept consee4 5		//"Your part is done."




//THE EYE
concept eye01 4 	//"Comes a man to rescue me?..."
concept eye02 4 	//"SSSSSo, you've returned with the talismans..."
concept eye03 4 	//"I am the Eye, trapped on this altar..."
concept eye04 4 	//"Well done, thief!  
concept eye05 4 	//"Leaving so soon?..."
concept eye06 4 	//"Where are you going?..."
concept eye07 4 	//"Poor Murus!  Still struggling.."
concept eye08 4 	//"Now you have your precious eye..."
concept eye09 4 	//"Master!  Beware! .."	

//MURUS		
concept murmut 8		//Muttering
concept murint 8 		//Intro
concept murdeal 8		//Offering Garrett a deal
concept murros1 8		//Rosary
concept murros2 8 	//During Rosary
concept murros3 8		//Post Rosary
concept mursym1 8		//HOLY SYMBOL
concept mursym2 8		//DURING SYMBOL
concept mursym3 8		//Post 
concept murbook1 8 	//BOOK
concept murbook2 8 	//DURING BOOK
concept murbook3 8	//POST BOOK		
concept murcand1 8 	//CANDLE
concept murcand2 8 	//DURING CANDLE		
concept murcand3 8 	//POST CANDLE
concept murgrav 8		//GRAVE
concept murrit1 8 	//RITUAL BEADS
concept murrit2 8 	//RITUAL CANDLE
concept murrit3 8		//RITUAL BOOK	
concept murrit4 8 	//RITUAL SYMBOL	
concept murbad 8		//SYMBOL IS BAD 
concept murrit5 8		//RITUAL COMPLETE	
concept murbur 8		//BURIAL
//concept murren 8	//RENAULT
concept murren1 8   	//RENAULT 1
concept murren2 8		//RENAULT 2
concept murmart 8 	//MARTELLO	
concept murhau1 8 	//HAUNTS
concept murhau2 8 	//HAUNTS2	
concept murfin 8		//FINAL

//RENAULT
concept renthank 4 	//THANKYOU

//HERMIT -ONE LONG FILE
concept hmt12200 7	//Reenacts Opera saga

//HERMIT -SAME SPEECH DONE AS A CONVERSATION
concept hmt122 7		//"I spy you little fish..."



////////
//TAGS//
////////

//UNUSED INTEGER TAGS
//tag_int DistanceRating
//tag_int MovementRating
//tag_int LightRating
//tag_int RelativeZPos
//tag_int Size

tag_int Mission
tag_int NearbyFriends
tag_int Reiterate
tag_int LineNo

//UNUSED TAGS
//tag PlayerMedium Water Air
//tag Startled  

tag Sense Sight Sound			//how does the AI sense the player
tag ComBal Winning Even Losing  	//how is AI doing in combat
tag CarryBody				//does AI see player carrying a a body
tag Reacquire True False   		//does the AI see for the 2nd+ time?
tag Investigate True False  		//is the AI looking for the player?

//////////
//VOICES//
//////////

//voice archetype known to be unused, where we can temporarily
//hide voices which are causing problems.  Ick.

//voice dummy archetype object

voice fnordvox

//TESTVOICE
voice testvoice

//KEEPER DETECTOR
voice vkeeper2

//GUARDS
voice guards

voice guard3 
archetype guards

voice guard2 
archetype guards

voice guard1
archetype guards

//DRUNK GUARD
voice drunk1

//SPARRING GUARD in TRAINING MISSION
voice vspar

//ASSASSIN 1 in MISSION 5
voice vass1

//ASSASSIN 2 in MISSION 5
voice vass2


//HAMMERS
voice hammrs

voice hammer3
archetype hammrs

voice hammer2
archetype hammrs

voice hammer1
archetype hammrs

//PRISONERS
voice prisoners

voice pris2
archetype prisoners

voice pris1
archetype prisoners

//SERVANTS
voice normals

voice normal2   //Female
archetype normals

voice normal1   //Male
archetype normals

//RAMIREZ
voice vramirez

//MURUS
voice vmurus

//RENAULT
voice vrenault

//CONSTANTINE
voice vcon

//THE EYE
voice veye

//CRITTERS
voice vfire

voice vburr

voice vhaunt

voice vzomb

voice vcray

voice vspider

voice vbug

voice vappar

voice vfrog

voice vapes

voice vape1
archetype vapes

voice vape2
archetype vapes


//THIEFGOLD VOICES

voice vhermit

voice vactor1	//Male opera actor

voice vactor2	//Female opera actor

voice vpatron1	//Male opera patron

voice vpatron2	//Female opera patron

voice vthieves	//Thieve's guild guys

voice vthief1	
archetype vthieves

voice vthief2
archetype vthieves

voice vmages	//Mage's tower guys

voice vmage1
archetype vmages

voice vmage2
archetype vmages

voice vair		//Air Elemental

voice vshrimp	//Little guy in outtakes miss18




