//SERVANT CONVERSATIONS

//CONV 1  "Peaceful, i'nt it?"		
schema sv1c0101
archetype SV_CONV
sv1c0101
schema_voice normal1 1 sv_c01 (LineNo 1 1)

schema sv2c0102
archetype SV_CONV
sv2c0102
schema_voice normal2 1 sv_c01 (LineNo 2 2)

schema sv1c0103
archetype SV_CONV
sv1c0103
schema_voice normal1 1 sv_c01 (LineNo 3 3)

schema sv2c0104
archetype SV_CONV
sv2c0104
schema_voice normal2 2 sv_c01 (LineNo 4 4)


//CONV 2, missions 2,5  "I swear, I've never seen...		
schema sv2c0201
archetype SV_CONV
sv2c0201
schema_voice normal2 1 sv_c02 (LineNo 1 1)
	
schema sv1c0202
archetype SV_CONV
sv1c0202
schema_voice normal1 1 sv_c02 (LineNo 2 2)

schema sv2c0203
archetype SV_CONV
sv2c0203
schema_voice normal2 1 sv_c02 (LineNo 3 3)

schema sv1c0204
archetype SV_CONV
sv1c0204
schema_voice normal1 1 sv_c02 (LineNo 4 4)


//CONV 3, missions 2,5 -"You'd never believe..."
schema sv1c0301
archetype SV_CONV
sv1c0301
schema_voice normal1 1 sv_c03 (LineNo 1 1)

schema sv2c0302	
archetype SV_CONV
sv2c0302
schema_voice normal2 1 sv_c03 (LineNo 2 2)

schema sv1c0303
archetype SV_CONV
sv1c0303
schema_voice normal1 1 sv_c03 (LineNo 3 3)
	
schema sv2c0304
archetype SV_CONV
sv2c0304
schema_voice normal2 1 sv_c03 (LineNo 4 4)

	
//CONV 4, missions 2,5  "Cook says the Sir's...		
schema sv2c0401
archetype SV_CONV
sv2c0401
schema_voice normal2 1 sv_c04 (LineNo 1 1)

schema sv1c0402
archetype SV_CONV
sv1c0402
schema_voice normal1 1 sv_c04 (LineNo 2 2)

schema sv2c0403
archetype SV_CONV
sv2c0403
schema_voice normal2 1 sv_c04 (LineNo 3 3)


//CONV 5, missions 2,5 "I don't think the garden mint...		
schema sv1c0501
archetype SV_CONV
sv1c0501
schema_voice normal1 1 sv_c05 (LineNo 1 1)

schema sv2c0502
archetype SV_CONV
sv2c0502
schema_voice normal2 1 sv_c05 (LineNo 2 2)	

schema sv1c0503
archetype SV_CONV
sv1c0503
schema_voice normal1 1 sv_c05 (LineNo 3 3)

schema sv2c0504
archetype SV_CONV
sv2c0504
schema_voice normal2 1 sv_c05 (LineNo 4 4)


//CONV 6, missions 2,5  "Remember back when..."		
schema sv2c0601
archetype SV_CONV
sv2c0601
schema_voice normal2 1 sv_c06 (LineNo 1 1)

schema sv1c0602
archetype SV_CONV
sv1c0602
schema_voice normal1 1 sv_c06 (LineNo 2 2)

schema sv2c0603
archetype SV_CONV
sv2c0603
schema_voice normal2 1 sv_c06 (LineNo 3 3)

schema sv1c0604
archetype SV_CONV
sv1c0604
schema_voice normal1 1 sv_c06 (LineNo 4 4)

schema sv2c0605
archetype SV_CONV
sv2c0605
schema_voice normal2 1 sv_c06 (LineNo 5 5)

schema sv1c0606
archetype SV_CONV
sv1c0606
schema_voice normal1 1 sv_c06 (LineNo 6 6)


//CONV 7, missions 2,5  "Coming from market..."	
schema sv1c0701
archetype SV_CONV
sv1c0701
schema_voice normal1 1 sv_c07 (LineNo 1 1)

schema sv2c0702
archetype SV_CONV
sv2c0702
schema_voice normal2 1 sv_c07 (LineNo 2 2)

schema sv1c0703
archetype SV_CONV
sv1c0703
schema_voice normal1 1 sv_c07 (LineNo 3 3)

schema sv2c0704
archetype SV_CONV
sv2c0704
schema_voice normal2 1 sv_c07 (LineNo 4 4)

schema sv1c0705
archetype SV_CONV
sv1c0705
schema_voice normal1 1 sv_c07 (LineNo 5 5)


//CONV 8, missions 2,5  "[long sigh].."  "What's wrong"	
schema sv2c0801
archetype SV_CONV
sv2c0801	
schema_voice normal2 1 sv_c08 (LineNo 1 1)

schema sv1c0802	 
archetype SV_CONV
sv1c0802
schema_voice normal1 1 sv_c08 (LineNo 2 2)

schema sv2c0803
archetype SV_CONV
sv2c0803
schema_voice normal2 1 sv_c08 (LineNo 3 3)

schema sv1c0804
archetype SV_CONV
sv1c0804
schema_voice normal1 1 sv_c08 (LineNo 4 4)

schema sv2c0805
archetype SV_CONV
sv2c0805
schema_voice normal2 1 sv_c08 (LineNo 5 5)


//CONV 9, missions 2,5  "Do you ever feel like..."		
schema sv1c0901
archetype SV_CONV
sv1c0901
schema_voice normal1 1 sv_c09 (LineNo 1 1)

schema sv2c0902
archetype SV_CONV
sv2c0902
schema_voice normal2 1 sv_c09 (LineNo 2 2)	

schema sv1c0903
archetype SV_CONV
sv1c0903
schema_voice normal1 1 sv_c09 (LineNo 3 3)

schema sv2c0904
archetype SV_CONV
sv2c0904
schema_voice normal2 1 sv_c09 (LineNo 4 4)


//CONV 10, missions 2,5  " You ever go down by… you know… "	
schema sv2c1001
archetype SV_CONV
sv2c1001
schema_voice normal2 1 sv_c10 (LineNo 1 1)

schema sv1c1002
archetype SV_CONV
sv1c1002
schema_voice normal1 1 sv_c10 (LineNo 2 2)

schema sv2c1003
archetype SV_CONV
sv2c1003
schema_voice normal2 1 sv_c10 (LineNo 3 3)

schema sv1c1004
archetype SV_CONV
sv1c1004
schema_voice normal1 1 sv_c10 (LineNo 4 4)

schema sv2c1005
archetype SV_CONV
sv2c1005
schema_voice normal2 1 sv_c10 (LineNo 5 5)

schema sv1c1006
archetype SV_CONV
sv1c1006
schema_voice normal1 1 sv_c10 (LineNo 6 6)


//CONV 11, missions 2,5 "Everything okay?"
schema sv1c1101
archetype SV_CONV
sv1c1101
schema_voice normal1 1 sv_c11 (LineNo 1 1)

schema sv2c1102
archetype SV_CONV
sv2c1102
schema_voice normal2 1 sv_c11 (LineNo 2 2)
	

//CONV 12, missions 2,5	"How's your day?"	
schema sv1c1201
archetype SV_CONV	
sv1c1201
schema_voice normal1 1 sv_c12 (LineNo 1 1)

schema sv2c1202
archetype SV_CONV
sv2c1202
schema_voice normal2 1 sv_c12 (LineNo 2 2)


//CONV 13, missions 2,5	"Seen Cook around?"
schema sv1c1301
archetype SV_CONV
sv1c1301
schema_voice normal1 1 sv_c13 (LineNo 1 1)

schema sv2c1302
archetype SV_CONV
sv2c1302
schema_voice normal2 1 sv_c13 (LineNo 2 2)

	
//CONV 14, missions 2,5 	"You still up?"		
schema sv1c1401
archetype SV_CONV
sv1c1401
schema_voice normal1 1 sv_c14 (LineNo 1 1)

schema sv2c1402
archetype SV_CONV
sv2c1402
schema_voice normal2 1 sv_c14 (LineNo 2 2)


//CONV 15, missions 2,5		
schema sv2c1501
archetype SV_CONV
sv2c1501
schema_voice normal2 1 sv_c15 (LineNo 1 1)
	
schema sv1c1502
archetype SV_CONV
sv1c1502
schema_voice normal1 1 sv_c15 (LineNo 2 2)


//CONV 16, missions 2,5 "I am so tired of muddy boots!"		
schema sv2c1601
archetype SV_CONV
sv2c1601
schema_voice normal2 1 sv_c16 (LineNo 1 1)

schema sv1c1602
archetype SV_CONV
sv1c1602
schema_voice normal1 1 sv_c16 (LineNo 2 2)


//CONV 17, missions 2,5 "You hear? The Sir.."
schema sv2c1701
archetype SV_CONV
sv2c1701
schema_voice normal2 1 sv_c17 (LineNo 1 1)
	
schema sv1c1702
archetype SV_CONV
sv1c1702
schema_voice normal1 1 sv_c17 (LineNo 2 2)


//CONV 18, missions 2,5 "You lose a button?"		
schema sv2c1801
archetype SV_CONV
sv2c1801
schema_voice normal2 1 sv_c18 (LineNo 1 1)

schema sv1c1802
archetype SV_CONV
sv1c1802
schema_voice normal1 1 sv_c18 (LineNo 2 2)


//CONV 19, mission 5 "What happened to young Brennan?"
schema sv1c1901
archetype SV_CONV
sv1c1901
schema_voice normal1 1 sv_c19 (LineNo 1 1)
	
schema sv2c1902
archetype SV_CONV
sv2c1902
schema_voice normal2 1 sv_c19 (LineNo 2 2)

schema sv1c1903	
archetype SV_CONV
sv1c1903
schema_voice normal1 1 sv_c19 (LineNo 3 3)


//THIEF GOLD///////////////////////////////////

//CONV 19, "Hit me."
schema sv106300
archetype SV_CONV
sv106300
schema_voice normal1 1 sv_063 (LineNo 1 1)

schema sv206301
archetype SV_CONV
sv206301
schema_voice normal2 1 sv_063 (LineNo 2 2)

schema sv106302
archetype SV_CONV
sv106302
schema_voice normal1 1 sv_063 (LineNo 3 3)

schema sv206303
archetype SV_CONV
sv206303
schema_voice normal2 1 sv_063 (LineNo 4 4)

schema sv106304
archetype SV_CONV
sv106304
schema_voice normal1 1 sv_063 (LineNo 5 5)

schema sv206305
archetype SV_CONV
sv206305
schema_voice normal2 1 sv_063 (LineNo 6 6)

schema sv106306
archetype SV_CONV
sv106306
schema_voice normal1 1 sv_063 (LineNo 7 7)


