//THIEF CONVERSATIONS

//#061  "When partners fight, it's never good."		
schema th106100
archetype OTHER_CONV
th106100
schema_voice vthief1 1 th_061 (LineNo 1 1)

schema th206101
archetype OTHER_CONV
th206101
schema_voice vthief2 1 th_061 (LineNo 2 2)

schema th106102
archetype OTHER_CONV
th106102
schema_voice vthief1 1 th_061 (LineNo 3 3)

schema th206103
archetype OTHER_CONV
th206103
schema_voice vthief2 1 th_061 (LineNo 4 4)



//#065 [HAMMER & THIEF] "By the builder I will find you..."		
schema hm106500
archetype OTHER_CONV
hm106500
schema_voice hammer1 1 th_065 (LineNo 1 1)

schema th106501
archetype OTHER_CONV
th106501
schema_voice vthief2 1 th_065 (LineNo 2 2)



//#066  "I hear some independent is doing		
schema th106600
archetype OTHER_CONV
th106600
schema_voice vthief1 1 th_066 (LineNo 1 1)

schema th206601
archetype OTHER_CONV
th206601
schema_voice vthief2 1 th_066 (LineNo 2 2)

schema th106602
archetype OTHER_CONV
th106602
schema_voice vthief1 1 th_066 (LineNo 3 3)



//#067  "Bafford was furious when he got back..."	
schema th106700
archetype OTHER_CONV
th106700
schema_voice vthief1 1 th_067 (LineNo 1 1)

schema th206701
archetype OTHER_CONV
th206701
schema_voice vthief2 1 th_067 (LineNo 2 2)

schema th106702
archetype OTHER_CONV
th106702
schema_voice vthief1 1 th_067 (LineNo 3 3)

schema th206703
archetype OTHER_CONV
th206703
schema_voice vthief2 1 th_067 (LineNo 4 4)

schema th106704
archetype OTHER_CONV
th106704
schema_voice vthief1 1 th_067 (LineNo 5 5)


//#068  "Did you here what happened to Gibbson.."
schema th106800
archetype OTHER_CONV
th106800
schema_voice vthief1 1 th_068 (LineNo 1 1)

schema th206801
archetype OTHER_CONV
th206801
schema_voice vthief2 1 th_068 (LineNo 2 2)

schema th106802
archetype OTHER_CONV
th106802
schema_voice vthief1 1 th_068 (LineNo 3 3)

schema th206803
archetype OTHER_CONV
th206803
schema_voice vthief2 1 th_068 (LineNo 4 4)

schema th106804
archetype OTHER_CONV
th106804
schema_voice vthief1 1 th_068 (LineNo 5 5)

schema th206805
archetype OTHER_CONV
th206805
schema_voice vthief2 1 th_068 (LineNo 6 6)

schema th106806
archetype OTHER_CONV
th106806
schema_voice vthief1 1 th_068 (LineNo 7 7)

schema th206807
archetype OTHER_CONV
th206807
schema_voice vthief2 1 th_068 (LineNo 8 8)

schema th106808
archetype OTHER_CONV
th106808
schema_voice vthief1 1 th_068 (LineNo 9 9)

schema th206809
archetype OTHER_CONV
th206809
schema_voice vthief2 1 th_068 (LineNo 10 10)

schema th106810
archetype OTHER_CONV
th106810
schema_voice vthief1 1 th_068 (LineNo 11 11)

schema th206811
archetype OTHER_CONV
th206811
schema_voice vthief2 1 th_068 (LineNo 12 12)

schema th106812
archetype OTHER_CONV
th106812
schema_voice vthief1 1 th_068 (LineNo 13 13)


//#069  "Y'hear about Sutter's job last night?"
schema th106900
archetype OTHER_CONV
th106900
schema_voice vthief1 1 th_069 (LineNo 1 1)

schema th206901
archetype OTHER_CONV
th206901
schema_voice vthief2 1 th_069 (LineNo 2 2)

schema th106902
archetype OTHER_CONV
th106902
schema_voice vthief1 1 th_069 (LineNo 3 3)

schema th206903
archetype OTHER_CONV
th206903
schema_voice vthief2 1 th_069 (LineNo 4 4)

schema th106904
archetype OTHER_CONV
th106904
schema_voice vthief1 1 th_069 (LineNo 5 5)

schema th106905
archetype OTHER_CONV
th106905
schema_voice vthief1 1 th_069 (LineNo 6 6)

schema th206906
archetype OTHER_CONV
th206906
schema_voice vthief2 1 th_069 (LineNo 7 7)

schema th106907
archetype OTHER_CONV
th106907
schema_voice vthief1 1 th_069 (LineNo 8 8)

schema th206908
archetype OTHER_CONV
th206908
schema_voice vthief2 1 th_069 (LineNo 9 9)

schema th106909
archetype OTHER_CONV
th106909
schema_voice vthief1 1 th_069 (LineNo 10 10)



//#071 [GUARD & 2 THIEVES] "Password"		
schema sg107100
archetype OTHER_CONV
sg107100
schema_voice guard1 1 th_071 (LineNo 1 1)

schema th107101
archetype OTHER_CONV
th107101
schema_voice vthief1 1 th_071 (LineNo 2 2)

schema sg107102
archetype OTHER_CONV
sg107102
schema_voice guard1 1 th_071 (LineNo 3 3)

schema th107103
archetype OTHER_CONV
th107103
schema_voice vthief1 1 th_071 (LineNo 4 4)

schema sg107104
archetype OTHER_CONV
sg107104
schema_voice guard1 1 th_071 (LineNo 5 5)

schema th207105
archetype OTHER_CONV
th207105
schema_voice vthief2 1 th_071 (LineNo 6 6)

schema sg107106
archetype OTHER_CONV
sg107106
schema_voice guard1 1 th_071 (LineNo 7 7)

schema th207107
archetype OTHER_CONV
th207107
schema_voice vthief2 1 th_071 (LineNo 8 8)

schema th107108
archetype OTHER_CONV
th107108
schema_voice vthief1 1 th_071 (LineNo 9 9)








